service:
  name: collector-manager

plugins:
  - serverless-hooks-plugin
  - serverless-s3-sync

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1

custom:
  hooks:
    before:package:createDeploymentArtifacts:
      - npm run build-prod
  s3Sync:
    - bucketName: collector-manager
      localDir: dist/collector-manager
      acl: public-read