package:
  exclude:
    - secrets.yml

service:
  name: collector-manager

plugins:
  - serverless-hooks-plugin
  - serverless-s3-sync

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1

# resources:
#   Resources:
#     PostgresSqlRdsInstance: ${file(./src/resources/rds/PostgreSqlRDSInstance.yml)}    


custom:
  stage: ${opt:stage, 'dev'}    
  config: file(./src/config/${self:custom.stage}.json) 
  secrets: ${file(secrets.yml)}

  hooks:
    before:package:createDeploymentArtifacts:
      - npm run build-prod
  s3Sync:
    - bucketName: collector-manager
      localDir: dist/collector-manager
      acl: public-read