POST https://24mdfdusj8.execute-api.eu-central-1.amazonaws.com/dev/users

{
    "first_name":"first name2",
    "last_name":"last name",
    "email":"email"
}

###

GET https://24mdfdusj8.execute-api.eu-central-1.amazonaws.com/dev/users

###
GET https://24mdfdusj8.execute-api.eu-central-1.amazonaws.com/dev/users/1


###
 PUT https://24mdfdusj8.execute-api.eu-central-1.amazonaws.com/dev/users/1
 
 {
    "first_name":"first_updated2",
    "last_name":"last_updated22",
    "email":"email_updated"
 }

###
DELETE https://24mdfdusj8.execute-api.eu-central-1.amazonaws.com/dev/users/21