# DependsOn: ServerlessVPCGA
 Type: AWS::RDS::DBInstance
 Properties:
   MasterUsername: root
   MasterUserPassword: "${self:custom.secrets.POSTGRES_PASS}"
  AllocatedStorage: 20
  DBName: ${self:custom.config.DB_NAME}
  DBInstanceClass: db.t2.micro
   VPCSecurityGroups:
   - sg-0704f1dd6a74e1d6f
#   DBSubnetGroupName:
#     Ref: ServerlessSubnetGroup
#   Engine: postgres
#   PubliclyAccessible: true
custom:
  stage: ${opt:stage, 'dev'}
  secrets: ${file(../../../secrets.yml):${self:custom.stage}}
  config: file(../../config/${self:custom.stage}.json)

  #https://github.com/serverless/examples